version: '3'
services: 
  db: 
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=kseniamahorkina
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=portfolio
  backend:
    image: node:10.15
    build: .
    restart: always
    links:
      - db:database
    ports: 
      - "8080:8080"
    depends_on:
      - db  